[k3s]
192.168.1.19 ansible_user=vagrant ansible_ssh_pass=vagrant

[monitoring]
192.168.1.22 ansible_user=vagrant ansible_ssh_pass=vagrant

[all:vars]
# Pour se connnecter sans bloquer sur la vérification de la clé SSH
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_become_pass=vagrant
